apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  S3_BUCKET_NAME: Ym10LS0zOTA4NDQ3NTY3MjE=
  AWS_ACCESS_KEY_ID: QUtJQVZXQUJKV0xZVUhHVUo2SFg=
  AWS_SECRET_ACCESS_KEY: Q3VmNkFPbEhaVUNjUWNpa0FNWUJTVXlqRW9zZkYyVFJDSE9kcWVWVQ==

---
apiVersion: v1
kind: Secret
metadata:
  name: firebase-key-secret
type: Opaque
stringData:
  key.json: |
    {
      "type": "service_account",
      "project_id": "your-project-id",
      "private_key_id": "your-private-key-id",
      "private_key": "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n",
      "client_email": "your-client-email@project-id.iam.gserviceaccount.com",
      "client_id": "your-client-id",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/your-client-email%40project-id.iam.gserviceaccount.com"
    }
